---
- name: set http_proxy
  lineinfile: dest=/etc/environment regexp='^http_proxy' line='http_proxy="{{ http_proxy }}"'
  when: http_proxy is defined

- name: set https_proxy
  lineinfile: dest=/etc/environment regexp='^https_proxy' line='https_proxy="{{ http_proxy }}"'
  when: http_proxy is defined
  
- name: keep proxy setting when using sudo
  lineinfile: dest=/etc/sudoers regexp='http_proxy' insertafter='^Defaults +env_keep \+=' line='Defaults    env_keep += "http_proxy https_proxy"'
  when: http_proxy is defined